package utility

import androidx.compose.runtime.compositionLocalOf

class Strings(
    // Common
    val back: String,
    val cancel: String,
    val language: String,

    // Main menu
    val play: String,
    val playSolo: String,
    val settings: String,
    val ballTypes: String,
    val watchAdToUnlock: String,
    val watchAdLoading: String,
    val comeBackTomorrow: String,
    val nextAdIn: (String) -> String,
    val percentUnlocked: (Int) -> String,

    // Difficulty dialog
    val chooseDifficulty: String,
    val easy: String,
    val medium: String,
    val hard: String,

    // Settings
    val settingsTitle: String,
    val gameplay: String,
    val ballSizeLabel: String,
    val ballSizeSmall: String,
    val ballSizeDefault: String,
    val ballSizeLarge: String,
    val chargeSpeedLabel: String,
    val speedSlow: String,
    val speedNormal: String,
    val speedFast: String,
    val speedFastest: String,
    val gameSpeedLabel: String,
    val pointsToWinLabel: String,
    val timeLimitLabel: String,
    val minuteShort: String,
    val sound: String,
    val soundMaster: String,
    val soundBackground: String,
    val soundFx: String,
    val mute: String,
    val muted: String,
    val visual: String,
    val tailLengthLabel: String,
    val tailNone: String,
    val tailShort: String,
    val tailDefault: String,
    val tailLong: String,
    val highPlayerArrow: String,
    val lowPlayerArrow: String,
    val highPlayerChargeFill: String,
    val lowPlayerChargeFill: String,
    val darkMode: String,
    val resetDefaults: String,

    // Ball unlock
    val ballTypesTitle: String,
    val watchAdsToUnlockMore: String,
    val watchAdEarn: String,
    val getPro: String,
    val restorePurchases: String,
    val unlocked: String,
    val reachPercent: (Int) -> String,
) {
    companion object {
        fun forCode(code: String): Strings = when (code) {
            "de" -> de()
            "es" -> es()
            "fr" -> fr()
            "ja" -> ja()
            "zh" -> zh()
            else -> en()
        }

        private fun en() = Strings(
            back = "← Back",
            cancel = "Cancel",
            language = "Language",
            play = "PLAY",
            playSolo = "PLAY SOLO",
            settings = "SETTINGS",
            ballTypes = "BALL TYPES",
            watchAdToUnlock = "Watch Ad to Unlock",
            watchAdLoading = "Watch Ad (Loading...)",
            comeBackTomorrow = "Come Back Tomorrow",
            nextAdIn = { "Next Ad in $it" },
            percentUnlocked = { "$it% Unlocked" },
            chooseDifficulty = "Choose Difficulty",
            easy = "Easy",
            medium = "Medium",
            hard = "Hard",
            settingsTitle = "SETTINGS",
            gameplay = "Gameplay",
            ballSizeLabel = "Ball Size",
            ballSizeSmall = "Small",
            ballSizeDefault = "Default",
            ballSizeLarge = "Large",
            chargeSpeedLabel = "Charge Speed",
            speedSlow = "Slow",
            speedNormal = "Normal",
            speedFast = "Fast",
            speedFastest = "Fastest",
            gameSpeedLabel = "Game Speed",
            pointsToWinLabel = "Points to Win",
            timeLimitLabel = "Time Limit",
            minuteShort = "min",
            sound = "Sound",
            soundMaster = "Master",
            soundBackground = "Background",
            soundFx = "Sound FX",
            mute = "Mute",
            muted = "Muted",
            visual = "Visual",
            tailLengthLabel = "Tail Length",
            tailNone = "None",
            tailShort = "Short",
            tailDefault = "Default",
            tailLong = "Long",
            highPlayerArrow = "High Player Arrow",
            lowPlayerArrow = "Low Player Arrow",
            highPlayerChargeFill = "High Player Charge Fill",
            lowPlayerChargeFill = "Low Player Charge Fill",
            darkMode = "Dark Mode",
            resetDefaults = "Reset to Defaults",
            ballTypesTitle = "BALL TYPES",
            watchAdsToUnlockMore = "Watch ads to unlock more ball types",
            watchAdEarn = "Watch Ad (+2%)",
            getPro = "Get Pro",
            restorePurchases = "Restore Purchases",
            unlocked = "Unlocked",
            reachPercent = { "Reach $it%" },
        )

        private fun de() = Strings(
            back = "← Zurück",
            cancel = "Abbrechen",
            language = "Sprache",
            play = "Spielen",
            playSolo = "Alleine spielen",
            settings = "Einstellungen",
            ballTypes = "Bälle",
            watchAdToUnlock = "Werbung ansehen zum Freischalten",
            watchAdLoading = "Werbung (Lädt...)",
            comeBackTomorrow = "Komm morgen wieder",
            nextAdIn = { "Nächste Werbung in $it" },
            percentUnlocked = { "$it% freigeschaltet" },
            chooseDifficulty = "Schwierigkeit wählen",
            easy = "Leicht",
            medium = "Mittel",
            hard = "Schwer",
            settingsTitle = "Einstellungen",
            gameplay = "Spielmodus",
            ballSizeLabel = "Ballgröße",
            ballSizeSmall = "Klein",
            ballSizeDefault = "Standard",
            ballSizeLarge = "Groß",
            chargeSpeedLabel = "Ladegeschwindigkeit",
            speedSlow = "Langsam",
            speedNormal = "Standard",
            speedFast = "Schnell",
            speedFastest = "Am schnellsten",
            gameSpeedLabel = "Spielgeschwindigkeit",
            pointsToWinLabel = "Punkte zum Gewinnen",
            timeLimitLabel = "Zeitlimit",
            minuteShort = "min",
            sound = "Sound",
            soundMaster = "Hauptlautstärke",
            soundBackground = "Hintergrundmusik",
            soundFx = "Soundeffekte",
            mute = "Stumm",
            muted = "Stummgeschaltet",
            visual = "Visuelle",
            tailLengthLabel = "Schweiflänge",
            tailNone = "Kein",
            tailShort = "Kurz",
            tailDefault = "Standard",
            tailLong = "Lang",
            highPlayerArrow = "Pfeil des oberen Spielers",
            lowPlayerArrow = "Pfeil des unteren Spielers",
            highPlayerChargeFill = "Ladebalken des oberen Spielers",
            lowPlayerChargeFill = "Ladebalken des unteren Spielers",
            darkMode = "Dunkelmodus",
            resetDefaults = "Standardwerte wiederherstellen",
            ballTypesTitle = "Bälle freischalten",
            watchAdsToUnlockMore = "Werbung ansehen, um mehr Balltypen freizuschalten",
            watchAdEarn = "Werbung ansehen (+2%)",
            getPro = "Pro kaufen",
            restorePurchases = "Käufe wiederherstellen",
            unlocked = "Freigeschaltet",
            reachPercent = { "$it% erreichen" },
        )

        private fun es() = Strings(
            back = "← Atrás",
            cancel = "Cancelar",
            language = "Idioma",
            play = "Jugar",
            playSolo = "Jugar solo",
            settings = "Ajustes",
            ballTypes = "Pelotas",
            watchAdToUnlock = "Ver anuncio para desbloquear",
            watchAdLoading = "Ver anuncio (Cargando...)",
            comeBackTomorrow = "Vuelve mañana",
            nextAdIn = { "Próximo anuncio en $it" },
            percentUnlocked = { "$it% desbloqueado" },
            chooseDifficulty = "Elige la dificultad",
            easy = "Fácil",
            medium = "Medio",
            hard = "Difícil",
            settingsTitle = "Ajustes",
            gameplay = "Jugabilidad",
            ballSizeLabel = "Tamaño del balón",
            ballSizeSmall = "Pequeño",
            ballSizeDefault = "Predeterminado",
            ballSizeLarge = "Grande",
            chargeSpeedLabel = "Velocidad de carga",
            speedSlow = "Lento",
            speedNormal = "Predeterminado",
            speedFast = "Rápido",
            speedFastest = "Más rápido",
            gameSpeedLabel = "Velocidad del juego",
            pointsToWinLabel = "Puntos para ganar",
            timeLimitLabel = "Límite de tiempo",
            minuteShort = "min",
            sound = "Sonido",
            soundMaster = "Principal",
            soundBackground = "Fondo",
            soundFx = "Efectos de sonido",
            mute = "Silenciar",
            muted = "Silenciado",
            visual = "Visual",
            tailLengthLabel = "Longitud de la cola",
            tailNone = "Ninguna",
            tailShort = "Corta",
            tailDefault = "Predeterminada",
            tailLong = "Larga",
            highPlayerArrow = "Flecha del jugador superior",
            lowPlayerArrow = "Flecha del jugador inferior",
            highPlayerChargeFill = "Barra de carga del jugador superior",
            lowPlayerChargeFill = "Barra de carga del jugador inferior",
            darkMode = "Modo oscuro",
            resetDefaults = "Restaurar valores predeterminados",
            ballTypesTitle = "Desbloquear pelotas",
            watchAdsToUnlockMore = "Ver anuncios para desbloquear más tipos de pelota",
            watchAdEarn = "Ver anuncio (+2%)",
            getPro = "Conseguir Pro",
            restorePurchases = "Restaurar compras",
            unlocked = "Desbloqueado",
            reachPercent = { "Llega al $it%" },
        )

        private fun fr() = Strings(
            back = "← Retour",
            cancel = "Annuler",
            language = "Langue",
            play = "Jouer",
            playSolo = "Jouer seul",
            settings = "Paramètres",
            ballTypes = "Balles",
            watchAdToUnlock = "Regarder une pub pour débloquer",
            watchAdLoading = "Regarder pub (Chargement...)",
            comeBackTomorrow = "Reviens demain",
            nextAdIn = { "Prochaine pub dans $it" },
            percentUnlocked = { "$it% débloqué" },
            chooseDifficulty = "Choisir la difficulté",
            easy = "Facile",
            medium = "Moyen",
            hard = "Difficile",
            settingsTitle = "Paramètres",
            gameplay = "Gameplay",
            ballSizeLabel = "Taille de la balle",
            ballSizeSmall = "Petit",
            ballSizeDefault = "Défaut",
            ballSizeLarge = "Grand",
            chargeSpeedLabel = "Vitesse de charge",
            speedSlow = "Lent",
            speedNormal = "Défaut",
            speedFast = "Rapide",
            speedFastest = "Le plus rapide",
            gameSpeedLabel = "Vitesse du jeu",
            pointsToWinLabel = "Points pour gagner",
            timeLimitLabel = "Limite de temps",
            minuteShort = "min",
            sound = "Son",
            soundMaster = "Principal",
            soundBackground = "Fond",
            soundFx = "Effets sonores",
            mute = "Muet",
            muted = "Coupé",
            visual = "Visuel",
            tailLengthLabel = "Longueur de la traînée",
            tailNone = "Aucune",
            tailShort = "Courte",
            tailDefault = "Défaut",
            tailLong = "Longue",
            highPlayerArrow = "Flèche du joueur du haut",
            lowPlayerArrow = "Flèche du joueur du bas",
            highPlayerChargeFill = "Jauge de charge du joueur du haut",
            lowPlayerChargeFill = "Jauge de charge du joueur du bas",
            darkMode = "Mode sombre",
            resetDefaults = "Rétablir les valeurs par défaut",
            ballTypesTitle = "Débloquer les balles",
            watchAdsToUnlockMore = "Regarder des pubs pour débloquer plus de types de balles",
            watchAdEarn = "Regarder pub (+2%)",
            getPro = "Obtenir Pro",
            restorePurchases = "Restaurer les achats",
            unlocked = "Débloqué",
            reachPercent = { "Atteindre $it%" },
        )

        private fun ja() = Strings(
            back = "← 戻る",
            cancel = "キャンセル",
            language = "言語",
            play = "プレイ",
            playSolo = "1人でプレイ",
            settings = "設定",
            ballTypes = "ボール",
            watchAdToUnlock = "広告を見てアンロック",
            watchAdLoading = "広告（読込中...）",
            comeBackTomorrow = "明日また来てね",
            nextAdIn = { "次の広告まで$it" },
            percentUnlocked = { "$it% アンロック済み" },
            chooseDifficulty = "難易度を選択",
            easy = "かんたん",
            medium = "ふつう",
            hard = "むずかしい",
            settingsTitle = "設定",
            gameplay = "ゲームプレイ",
            ballSizeLabel = "ボールのサイズ",
            ballSizeSmall = "小さい",
            ballSizeDefault = "デフォルト",
            ballSizeLarge = "大きい",
            chargeSpeedLabel = "チャージ速度",
            speedSlow = "遅い",
            speedNormal = "デフォルト",
            speedFast = "速い",
            speedFastest = "最速",
            gameSpeedLabel = "ゲーム速度",
            pointsToWinLabel = "勝利ポイント",
            timeLimitLabel = "制限時間",
            minuteShort = "分",
            sound = "サウンド",
            soundMaster = "マスター",
            soundBackground = "BGM",
            soundFx = "効果音",
            mute = "ミュート",
            muted = "ミュート中",
            visual = "ビジュアル",
            tailLengthLabel = "尾の長さ",
            tailNone = "なし",
            tailShort = "短い",
            tailDefault = "デフォルト",
            tailLong = "長い",
            highPlayerArrow = "上プレイヤーの矢印",
            lowPlayerArrow = "下プレイヤーの矢印",
            highPlayerChargeFill = "上プレイヤーのチャージゲージ",
            lowPlayerChargeFill = "下プレイヤーのチャージゲージ",
            darkMode = "ダークモード",
            resetDefaults = "デフォルトに戻す",
            ballTypesTitle = "ボールをアンロック",
            watchAdsToUnlockMore = "広告を見てボールをアンロックしよう",
            watchAdEarn = "広告を見る (+2%)",
            getPro = "Proを取得",
            restorePurchases = "購入を復元",
            unlocked = "アンロック済み",
            reachPercent = { "$it%を達成" },
        )

        private fun zh() = Strings(
            back = "← 返回",
            cancel = "取消",
            language = "语言",
            play = "游玩",
            playSolo = "单人游玩",
            settings = "设置",
            ballTypes = "球",
            watchAdToUnlock = "观看广告解锁",
            watchAdLoading = "观看广告（加载中...）",
            comeBackTomorrow = "明天再来",
            nextAdIn = { "${it}后可看广告" },
            percentUnlocked = { "$it% 已解锁" },
            chooseDifficulty = "选择难度",
            easy = "简单",
            medium = "中等",
            hard = "困难",
            settingsTitle = "设置",
            gameplay = "玩法",
            ballSizeLabel = "球的大小",
            ballSizeSmall = "小",
            ballSizeDefault = "默认",
            ballSizeLarge = "大",
            chargeSpeedLabel = "蓄力速度",
            speedSlow = "慢",
            speedNormal = "默认",
            speedFast = "快",
            speedFastest = "最快",
            gameSpeedLabel = "游戏速度",
            pointsToWinLabel = "获胜所需分数",
            timeLimitLabel = "时间限制",
            minuteShort = "分钟",
            sound = "音效",
            soundMaster = "总音量",
            soundBackground = "背景音乐",
            soundFx = "音效",
            mute = "静音",
            muted = "已静音",
            visual = "视觉",
            tailLengthLabel = "尾迹长度",
            tailNone = "无",
            tailShort = "短",
            tailDefault = "默认",
            tailLong = "长",
            highPlayerArrow = "上方玩家箭头",
            lowPlayerArrow = "下方玩家箭头",
            highPlayerChargeFill = "上方玩家蓄力条",
            lowPlayerChargeFill = "下方玩家蓄力条",
            darkMode = "深色模式",
            resetDefaults = "恢复默认设置",
            ballTypesTitle = "解锁球",
            watchAdsToUnlockMore = "观看广告解锁更多球类型",
            watchAdEarn = "观看广告 (+2%)",
            getPro = "获取专业版",
            restorePurchases = "恢复购买",
            unlocked = "已解锁",
            reachPercent = { "达到$it%" },
        )
    }
}

val LocalStrings = compositionLocalOf { Strings.forCode("") }
